// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSqVEe1ea2w1k72_9yVJ1Rp9E6p9wp4kk',
    appId: '1:365904740247:web:dc6f6da722d3cad6ae8ed2',
    messagingSenderId: '365904740247',
    projectId: 'get-your-dev',
    authDomain: 'get-your-dev.firebaseapp.com',
    storageBucket: 'get-your-dev.appspot.com',
    measurementId: 'G-ZYRK0SX25Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfuGN8EgU2PGlj-_8cD1BCC4K4byDkoC0',
    appId: '1:365904740247:android:42c8097271948da9ae8ed2',
    messagingSenderId: '365904740247',
    projectId: 'get-your-dev',
    storageBucket: 'get-your-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCy6A2dFlWvExCnbnt0sSj9gqzBkczw_Y',
    appId: '1:365904740247:ios:e301649cb55aaa8bae8ed2',
    messagingSenderId: '365904740247',
    projectId: 'get-your-dev',
    storageBucket: 'get-your-dev.appspot.com',
    iosClientId: '365904740247-75dj3onhgg21mik46cl1v16rssdbvnq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.getYourDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCy6A2dFlWvExCnbnt0sSj9gqzBkczw_Y',
    appId: '1:365904740247:ios:e301649cb55aaa8bae8ed2',
    messagingSenderId: '365904740247',
    projectId: 'get-your-dev',
    storageBucket: 'get-your-dev.appspot.com',
    iosClientId: '365904740247-75dj3onhgg21mik46cl1v16rssdbvnq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.getYourDev',
  );
}
